# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install PowerShell
        run: sudo apt-get install powershell
      - name: Install Pester
        run: pwsh -c "Install-Module -Name Pester -Force"
      - name: Import Pester
        run: pwsh -c "Import-Module Pester -PassThru"
      - name: Run tests
        run: pwsh -c "Invoke-Pester -Passthru -ExcludeTag "Integration", "Dummy", "Draft""
        #run: pwsh -c "Invoke-Pester -Passthru -CodeCoverage (Get-ChildItem -Path $PSScriptRoot\*.ps1 -Exclude *.Tests.* ).FullName -ExcludeTag "Integration", "Dummy", "Draft" | Export-NUnitReport -Path NUnitReport.xml"

  build:
    needs: unit-test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PowerShell
        run: echo hello build step

  ubuntu-integration-test:
    needs: build
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PowerShell
        run: echo Ubuntu Testing

  windows-integration-test:
    needs: build
    if: ${{ success() }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PowerShell
        run: echo Windows Testing

  macos-integration-test:
    needs: build
    if: ${{ success() }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PowerShell
        run: echo MacOS Testing

  deploy:
    needs: [ubuntu-integration-test, windows-integration-test, macos-integration-test]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PowerShell
        run: echo ohoy deploy

  merge:
    needs: deploy
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "snail mail"
          git config --local user.name ${{ github.actor }}
      - name: Merge to main
        run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff dev -m "Auto merge dev to main"
          git push
        