# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install PowerShell
        run: sudo apt-get install powershell
      - name: Install Pester
        run: pwsh -c "Install-Module -Name Pester -Force"
      - name: Import Pester
        run: pwsh -c "Import-Module Pester -PassThru"
      - name: Run tests
        run: pwsh -c "Invoke-Pester -Passthru -CodeCoverage -ExcludeTag "Integration", "Dummy", "Draft" | Export-JUnitReport -Path JUnitReport.xml"
      # Upload Test results
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: JUnitReport
          path: JUnitReport.xml
          retention-days: 5
      - name: Archive code coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.xml
          retention-days: 5



  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PowerShell
        run: echo hello build step